global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'atlas'
    static_configs:
      - targets: ['atlas:8000']
    metrics_path: '/metrics'

  - job_name: 'milvus'
    static_configs:
      - targets: ['milvus:9091']

  - job_name: 'temporal'
    static_configs:
      - targets: ['temporal:9090']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

rule_files:
  - 'rules/*.yml'

storage:
  tsdb:
    retention_time: 15d
    retention_size: 10GB