apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-ai
  labels:
    app: atlas-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: atlas-ai
  template:
    metadata:
      labels:
        app: atlas-ai
    spec:
      containers:
      - name: atlas-ai
        image: atlas-ai:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: ATLAS_VECTOR_DB_URL
          valueFrom:
            configMapKeyRef:
              name: atlas-config
              key: vector_db_url
        - name: ATLAS_VECTOR_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: atlas-config
              key: vector_db_port
        - name: ATLAS_WORKFLOW_ENGINE_URL
          valueFrom:
            configMapKeyRef:
              name: atlas-config
              key: workflow_engine_url
        - name: ATLAS_API_KEY
          valueFrom:
            secretKeyRef:
              name: atlas-secrets
              key: api_key
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: atlas-ai
spec:
  selector:
    app: atlas-ai
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atlas-config
data:
  vector_db_url: "milvus-service"
  vector_db_port: "19530"
  workflow_engine_url: "temporal-service:7233"
---
apiVersion: v1
kind: Secret
metadata:
  name: atlas-secrets
type: Opaque
data:
  api_key: base64encodedkey
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: atlas-ai-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: atlas-ai
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80